# permissions for end users to edit dnsproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dnsprovider-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-acme
    app.kubernetes.io/part-of: kube-acme
    app.kubernetes.io/managed-by: kustomize
  name: dnsprovider-editor-role
rules:
- apiGroups:
  - acme.ketches.cn
  resources:
  - dnsproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - acme.ketches.cn
  resources:
  - dnsproviders/status
  verbs:
  - get
