# permissions for end users to view certificaterequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: certificaterequest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-acme
    app.kubernetes.io/part-of: kube-acme
    app.kubernetes.io/managed-by: kustomize
  name: certificaterequest-viewer-role
rules:
- apiGroups:
  - acme.ketches.cn
  resources:
  - certificaterequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - acme.ketches.cn
  resources:
  - certificaterequests/status
  verbs:
  - get
