apiVersion: acme.ketches.cn/v1alpha1
kind: DNSProvider
metadata:
  labels:
    app.kubernetes.io/name: dnsprovider
    app.kubernetes.io/instance: dnsprovider-sample
    app.kubernetes.io/part-of: kube-acme
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-acme
  name: dnsprovider-sample
spec:
  # TODO(user): Add fields here
