apiVersion: acme.ketches.cn/v1alpha1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: certificate
    app.kubernetes.io/instance: certificate-sample
    app.kubernetes.io/part-of: kube-acme
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-acme
  name: certificate-sample
spec:
  # TODO(user): Add fields here
